### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Cleboost** [Zinidia/Pelinstaller#2]
* SUCCESS: Downloaded Pelican Panel files!

* Installing composer dependencies..
Composer could not detect the root package (pelican-dev/panel) version, defaulting to '1.0.0'. See https://getcomposer.org/root-version
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
89 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

* SUCCESS: Installed composer dependencies!

* Creating database user pelican...
* Database user pelican created
* Creating database panel...
* Granting all privileges on panel to pelican...
* Privileges granted
* Database panel created
* Configuring environment..

   INFO  Application key set successfully.  

 // The application URL MUST begin with https:// or http:// depending on if you are using SSL or not. If you do not     
 // include the scheme your emails and other content will link to the wrong location.                                   

 ! [NOTE] You've selected the Redis driver for one or more options, please provide valid connection information below.  
 !        In most cases you can use the defaults provided unless you have modified your setup.                          

 // By default a Redis server instance has no password as it is running locally and inaccessible to the outside world.  
 // If this is the case, simply hit enter without entering a value.                                                     

                                    
  The "1" argument does not exist.

**Comment by Zinidia** [comment]
Thank you for your report, it looks like the latest version of Pelican Panel unfortunately broke the redis driver in the `php artisan p:environment:setup` installation step, I went ahead and implemented [the necessary changes](https://github.com/pelican-installer/pelican-installer/commit/77220bca242523bad6a128074596bc57068532bc) to temporarily disable redis from our installation script.

**Comment by PythonTilk** [comment]
im still gtting this error

**Comment by Zinidia** [comment]
Hi, the error you were getting was likely not the same error but I discovered an issue with [a commit in the new Pelican update](https://github.com/pelican-dev/panel/commit/c0eedc16e026a15eb9e1bd4a52814b4e992117a0) which seems to have removed the ability to specify a panel url in installation args. I went ahead and [implemented a patch for this](https://github.com/Zinidia/Pelinstaller/commit/3f16ab50103a8523f05f1e277c174b98ad832357).
