### ISSUE TITLE
Egg error

### ISSUE THREAD

**Issue by Priv-8** [Zinidia/Pelinstaller#4]
Same error that eggs #3 .
OS used : Debian 12
Egg used : All eggs dont work (exemple : https://github.com/pelican-eggs/games-steamcmd/blob/main/core_keeper/egg-core-keeper.json)
Error : HTTP/1.1 500 Internal Server Error
![Screenshot_1](https://github.com/user-attachments/assets/ffc490e1-861e-4568-83c1-1c8649329219)

**Comment by Priv-8** [comment]
In addition : Import egg via URL work perfectly with the same problematic egg.

Probably an folder permission problem ?

**Comment by Priv-8** [comment]
I find the solution here : https://pelican.dev/docs/troubleshooting/
I'm NGINX user, i used this command : chown -R www-data:www-data /var/www/pelican 

The problem is solved now, probably add this command at the end of the script can prevent this issue.

Have a nice day :)

**Comment by Zinidia** [comment]
Hi thanks for your help, I went ahead and patched this issue in commit 
a3cd6d4. Just to clarify, this is an issue on Pelican's side but we added a temporary patch on our end.
