### ISSUE TITLE
Script won't ask for the mysql/mariaDB root password

### ISSUE THREAD

**Issue by sollevix67** [Zinidia/Pelinstaller#6]
The script isn't asking for the mysql/mariaDB root password and cause 
`ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)`

at the step : * Creating database user pelican...

**Comment by Zinidia** [comment]
I don't see why that would be needed, the script is meant to be run on a fresh installation before people mess with stuff like set a password for the MySQL root user.
