### ISSUE TITLE
Error While installing Wings after Panel was installed. Ubuntu 24.04 fresh install

### ISSUE THREAD

**Issue by robinhashtag-blip** [Zinidia/Pelinstaller#7]
Vorbereitung zum Entpacken von .../9-slirp4netns_1.2.1-1build2_amd64.deb ...
Entpacken von slirp4netns (1.2.1-1build2) ...
Fehler traten auf beim Bearbeiten von:
 /tmp/apt-dpkg-install-YHsvRs/1-containerd.io_1.7.23-1_amd64.deb
 /tmp/apt-dpkg-install-YHsvRs/3-docker-ce-cli_5%3a27.3.1-1~ubuntu.24.04~noble_amd64.deb
 /tmp/apt-dpkg-install-YHsvRs/4-docker-ce_5%3a27.3.1-1~ubuntu.24.04~noble_amd64.deb
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by Zinidia** [comment]
Hi, this error is likely unrelated to the installer but instead related to an issue with broken packages, I suggest reinstalling and then re-running the installer. If that doesn't work, please provide me with additional information about your environment including the distro version.

Thanks
